function anularDato(idData)
    connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
    )                                                                                                                                                                                    
    query = sprintf( ...
        'UPDATE producto_38 SET ESTADO_38=0 WHERE ID_PRODUCTO_38=%d', ...
        idData ...
        )
    execute(connexion, query)
    close(connexion);
    clear connexion query
end