function insertarDato(valueCan, presCos, presUni)
    connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
    )                                                                                                                                                                                    
    query = sprintf( ...
        ['INSERT INTO producto_38 (ESTADO_38, CANTIDAD_38, PRECIO_COSTO_38, PRECIO_UNITARIO_38) ' ...
        '        VALUES (%d, %d, %.2f, %.2f);'], 1, valueCan, presCos, presUni ...
        )
    execute(connexion, query)
    close(connexion);
    clear connexion query
end