function modificarDato(idProd, valueCan, presCos, presUni)
    connexion = database( ...
      'matlab', ...                                                                                                                                                                     
      'workbench', ...
      'workbench', ...
      'org.mariadb.jdbc.Driver', ...                                                                                                                                                    
      'jdbc:mariadb://127.0.0.1:3306/matlab' ...
    )                                                                                                                                                                                    
    query = sprintf( ...
        'UPDATE producto_38 SET CANTIDAD_38=%.2f, PRECIO_COSTO_38=%.2f, PRECIO_UNITARIO_38=%.2f WHERE ID_PRODUCTO_38=%d', ...
        valueCan, presCos, presUni, idProd ...
        );
    execute(connexion, query)
    close(connexion);
    clear connexion query
end